spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${AUTH_SERVICE_URL}
              predicates:
                - Path=/api/auth/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: authServiceCircuitBreaker
                    fallbackUri: forward:/auth-fallback
            - id: league-service
              uri: ${LEAGUE_SERVICE_URL}
              predicates:
                - Path=/api/league/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: leagueServiceCircuitBreaker
                    fallbackUri: forward:/league-fallback

jwt:
  secret: ${JWT_SECRET}