spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${AUTH_SERVICE_URL}
              predicates:
                - Path=/api/auth/**
            - id: league-service
              uri: ${LEAGUE_SERVICE_URL}
              predicates:
                - Path=/api/league/**

jwt:
  secret: ${JWT_SECRET}